version: "3.3"

services:
  app:
    build: .
    environment:
      - APP_NAME=app
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - redis
  chain-worker:
    build: .
    environment:
      - APP_NAME=chain-worker
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - redis
      - app
  validator-worker:
    build: .
    environment:
      - APP_NAME=validator-worker
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - redis
      - app
  block-worker:
    build: .
    environment:
      - APP_NAME=block-worker
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - redis
      - app
  redis:
    image: redislabs/rejson:latest
    restart: always
    expose:
      - 6379
    command: bash -c "redis-server --loadmodule /usr/lib/redis/modules/rejson.so --save 20 1 --loglevel warning && chmod 777 -R /data && chmod 777 -R /etc"
    volumes:
      - redis_data:/data
      - redis_etc:/etc

volumes:
  node_modules:
  redis_data:
  redis_etc: